spring:
  application:
    name: demo-curso-mongodb
  data:
    mongodb:
      uri: mongodb://localhost:27017/bd-demo

server:
  port: 8081
  
info:
  project:
    name: Project using MongoDB
    
ta:
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}
  url-token: ${URL_TOKEN}
  